@startuml

box "Application Process" #LightGray
actor "User" as u
participant "DeadlineMonitor" as dm
participant "Deadline" as d
participant "HealthMonitor" as hm
end box

participant "LaunchManager" as lm

u -> hm : Get DeadlineMonitor
hm --> u : DeadlineMonitor instance
u -> dm : Create Deadline
dm -> dm : Register deadline
dm --> u : Deadline instance

alt Deadline stopped before expiration

u -> d : Start
d --> u : Ok
hm -> dm : Check deadlines
note right : HealthMonitor does this in a background thread
dm --> hm : Ok
hm --> lm : Alive notification (IPC)
u -> d : Stop
d --> u : Ok
dm -> dm : Unregister deadline

else Deadline stopped after expiration

u -> d : Start
d --> u : Ok
hm -> dm : Check deadlines
note right : HealthMonitor does this in a background thread
dm -> dm : Deadline expired
dm --> hm : Failed
note right: Alive notification is not sent
u -> d : Stop
d --> u : Error
dm -> dm : Unregister deadline

else Deadline stopped while disabled

u -> d : Start
d --> u : Ok
u -> dm : Disable
dm --> u : Ok
hm -> dm : Check deadlines
note right : HealthMonitor does this in a background thread
dm --> hm : Ok
note right : The DeadlineMonitor is disabled, the deadlines are paused and not checked
hm --> lm : Alive notification (IPC)
u -> d : Stop
d --> u : Ok
dm -> dm : Unregister deadline
u -> dm : Enable
dm --> u : Ok

else Deadline expired after enabled

u -> d : Start
d --> u : Ok
u -> dm : Disable
dm --> u : Ok
hm -> dm : Check deadlines
note right : HealthMonitor does this in a background thread
dm --> hm : Ok
note right : The DeadlineMonitor is disabled, the deadlines are paused and not checked
u -> dm : Enable
dm --> u : Ok
hm -> dm : Check deadlines
note right : HealthMonitor does this in a background thread
dm -> dm : Deadline expired
dm --> hm : Failed
note right: Alive notification is not sent
u -> d : Stop
d --> u : Error
dm -> dm : Unregister deadline

end

@enduml
