@startuml

+enum HeartbeatMonitorStatus {
    Healthy
    Disabled
    TimedOut
}

+enum Error {
    BadParameter,
    NotAllowed,
    OutOfMemory,
    Generic,
}

+class HeartbeatMonitor {
    +new(maximum_heartbeat_cycle: Duration) -> Self
    +heartbeat(&self) -> Result<(), Error>
    +check_heartbeat(&self) -> Status
    +enable(&self) -> Result<(), Error>
    +disable(&self) -> Result<(), Error>
}

HeartbeatMonitor *-- HeartbeatMonitorStatus : owns
HeartbeatMonitor ..> Error
