@startuml

+enum Status {
    Running
    Disabled
    Failed
    Stopped
}

+enum Error {
    BadParameter,
    NotAllowed,
    OutOfMemory,
    Generic,
}

+class LogicMonitorState {
    +new<N: AsRef<str>>(name: N) -> Self
}

+class LogicMonitorBuilder {
    +new(initial_state: LogicMonitorState) -> Self
    +add_transition(&mut self, from: LogicMonitorState, to: LogicMonitorState) -> &mut Self
    +build(self) -> Result<LogicMonitor, Error>
}

+class LogicMonitor {
    +transition(&self, to: LogicMonitorState) -> Result<(), Error>
    +enable(&self) -> Result<(), Error>
    +disable(&self) -> Result<(), Error>
    +status(&self) -> Status
    +state(&self) -> LogicMonitorState
}

LogicMonitorBuilder ..> Error
LogicMonitorBuilder *-- "1..*" LogicMonitorState : owns
LogicMonitorBuilder ..> LogicMonitor : <<consumes>>
LogicMonitor *-- Status : owns
LogicMonitor *-- "1..*" LogicMonitorState : owns
LogicMonitor ..> Error
