name: 'Setup Rust Build Environment'
description: 'Checks out code, and caches cargo dependencies'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache cargo & target
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install cargo-tarpaulin if not already installed
      run: |
        if ! command -v cargo-tarpaulin > /dev/null; then
          cargo install cargo-tarpaulin --version 0.32.7 --locked
        else
          echo "cargo-tarpaulin is already installed"
        fi
      shell: bash
